#!/bin/sh
#
# This shell script will be called by REPLACELBPDATADIR/apccontrol when apcupsd
# loses contact with the UPS (i.e. the serial connection is not responding).
#

php -f REPLACELBPHTMLDIR/email.php `basename "$0"` `hostname` $1

exit 0
