#!/bin/sh
#
# This shell script will be called by REPLACELBPDATADIR/apccontrol when apcupsd
# restores contact with the UPS (i.e. the serial connection is restored).
#

php -f REPLACELBPHTMLDIR/email.php `basename "$0"` `hostname` $1

exit 0
